import PNG1 from "../assets/articles-imgs/PNG1.png";
import PNG2 from "../assets/articles-imgs/PNG2.png";
import PNG3 from "../assets/articles-imgs/PNG3.png";
import PNG4 from "../assets/articles-imgs/PNG4.png";
import PNG5 from "../assets/articles-imgs/PNG5.png";
import PNG6 from "../assets/articles-imgs/PNG6.png";
import PNG7 from "../assets/articles-imgs/PNG7.png";
import PNG8 from "../assets/articles-imgs/PNG8.png";
import PNG9 from "../assets/articles-imgs/PNG9.png";
import PNG10 from "../assets/articles-imgs/PNG10.png";
import PNG11 from "../assets/articles-imgs/PNG11.png";
import PNG12 from "../assets/articles-imgs/PNG12.png";
import PNG13 from "../assets/articles-imgs/PNG13.png";
import PNG14 from "../assets/articles-imgs/PNG14.png";
import PNG15 from "../assets/articles-imgs/PNG15.png";

export const NIKE_ARTICLES_DATA = [
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Purple",
    imgUrl: PNG1,
    price: "$299",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike White",
    imgUrl: PNG2,
    price: "$199",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Khaki",
    imgUrl: PNG3,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Red",
    imgUrl: PNG4,
    price: "$249",
    inventory: 19,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Fire",
    imgUrl: PNG5,
    price: "$799",
    inventory: 12,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Bumble",
    imgUrl: PNG6,
    price: "$459",
    inventory: 6,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Long",
    imgUrl: PNG7,
    price: "$295",
    inventory: 18,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Green",
    imgUrl: PNG8,
    price: "$499",
    inventory: 17,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Ojay",
    imgUrl: PNG9,
    price: "$495",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Cream",
    imgUrl: PNG10,
    price: "$999",
    inventory: 5,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Black Fire",
    imgUrl: PNG11,
    price: "$699",
    inventory: 16,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Black & White",
    imgUrl: PNG12,
    price: "$399",
    inventory: 8,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Sky Blue",
    imgUrl: PNG13,
    price: "$699",
    inventory: 7,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Colors",
    imgUrl: PNG14,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Ghost",
    imgUrl: PNG15,
    price: "$799",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Purple",
    imgUrl: PNG1,
    price: "$299",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike White",
    imgUrl: PNG2,
    price: "$199",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Khaki",
    imgUrl: PNG3,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Red",
    imgUrl: PNG4,
    price: "$249",
    inventory: 19,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Fire",
    imgUrl: PNG5,
    price: "$799",
    inventory: 12,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Bumble",
    imgUrl: PNG6,
    price: "$459",
    inventory: 6,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Long",
    imgUrl: PNG7,
    price: "$295",
    inventory: 18,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Green",
    imgUrl: PNG8,
    price: "$499",
    inventory: 17,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Ojay",
    imgUrl: PNG9,
    price: "$495",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Cream",
    imgUrl: PNG10,
    price: "$999",
    inventory: 5,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Black Fire",
    imgUrl: PNG11,
    price: "$699",
    inventory: 16,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Black & White",
    imgUrl: PNG12,
    price: "$399",
    inventory: 8,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Sky Blue",
    imgUrl: PNG13,
    price: "$699",
    inventory: 7,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Colors",
    imgUrl: PNG14,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Nike",
    name: "Nike Ghost",
    imgUrl: PNG15,
    price: "$799",
    inventory: 11,
  },
];

export const ADIDAS_ARTICLES_DATA = [
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Purple",
    imgUrl: PNG1,
    price: "$299",
    inventory: 13,
  },

  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas White",
    imgUrl: PNG2,
    price: "$199",
    inventory: 11,
  },

  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Bumble",
    imgUrl: PNG6,
    price: "$459",
    inventory: 6,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Long",
    imgUrl: PNG7,
    price: "$295",
    inventory: 18,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Green",
    imgUrl: PNG8,
    price: "$499",
    inventory: 17,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Ojay",
    imgUrl: PNG9,
    price: "$495",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Cream",
    imgUrl: PNG10,
    price: "$999",
    inventory: 5,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Black Fire",
    imgUrl: PNG11,
    price: "$699",
    inventory: 16,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Purple",
    imgUrl: PNG1,
    price: "$299",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas White",
    imgUrl: PNG2,
    price: "$199",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Khaki",
    imgUrl: PNG3,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Red",
    imgUrl: PNG4,
    price: "$249",
    inventory: 19,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Black & White",
    imgUrl: PNG12,
    price: "$399",
    inventory: 8,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Sky Blue",
    imgUrl: PNG13,
    price: "$699",
    inventory: 7,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Colors",
    imgUrl: PNG14,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Ghost",
    imgUrl: PNG15,
    price: "$799",
    inventory: 11,
  },

  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Fire",
    imgUrl: PNG5,
    price: "$799",
    inventory: 12,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Bumble",
    imgUrl: PNG6,
    price: "$459",
    inventory: 6,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Black Fire",
    imgUrl: PNG11,
    price: "$699",
    inventory: 16,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Black & White",
    imgUrl: PNG12,
    price: "$399",
    inventory: 8,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Sky Blue",
    imgUrl: PNG13,
    price: "$699",
    inventory: 7,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Colors",
    imgUrl: PNG14,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Ghost",
    imgUrl: PNG15,
    price: "$799",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Long",
    imgUrl: PNG7,
    price: "$295",
    inventory: 18,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Green",
    imgUrl: PNG8,
    price: "$499",
    inventory: 17,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Ojay",
    imgUrl: PNG9,
    price: "$495",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Adidas",
    name: "Adidas Cream",
    imgUrl: PNG10,
    price: "$999",
    inventory: 5,
  },
];

export const REEBOK_ARTICLES_DATA = [
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Purple",
    imgUrl: PNG1,
    price: "$299",
    inventory: 13,
  },

  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Fire",
    imgUrl: PNG5,
    price: "$799",
    inventory: 12,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Bumble",
    imgUrl: PNG6,
    price: "$459",
    inventory: 6,
  },

  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Green",
    imgUrl: PNG8,
    price: "$499",
    inventory: 17,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Ojay",
    imgUrl: PNG9,
    price: "$495",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Cream",
    imgUrl: PNG10,
    price: "$999",
    inventory: 5,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Black Fire",
    imgUrl: PNG11,
    price: "$699",
    inventory: 16,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok White",
    imgUrl: PNG2,
    price: "$199",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Khaki",
    imgUrl: PNG3,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Red",
    imgUrl: PNG4,
    price: "$249",
    inventory: 19,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Cream",
    imgUrl: PNG10,
    price: "$999",
    inventory: 5,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Colors",
    imgUrl: PNG14,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Black & White",
    imgUrl: PNG12,
    price: "$399",
    inventory: 8,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Sky Blue",
    imgUrl: PNG13,
    price: "$699",
    inventory: 7,
  },

  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Ghost",
    imgUrl: PNG15,
    price: "$799",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Purple",
    imgUrl: PNG1,
    price: "$299",
    inventory: 13,
  },

  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Black Fire",
    imgUrl: PNG11,
    price: "$699",
    inventory: 16,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Black & White",
    imgUrl: PNG12,
    price: "$399",
    inventory: 8,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Sky Blue",
    imgUrl: PNG13,
    price: "$699",
    inventory: 7,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Colors",
    imgUrl: PNG14,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Ghost",
    imgUrl: PNG15,
    price: "$799",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Fire",
    imgUrl: PNG5,
    price: "$799",
    inventory: 12,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Bumble",
    imgUrl: PNG6,
    price: "$459",
    inventory: 6,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Long",
    imgUrl: PNG7,
    price: "$295",
    inventory: 18,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Green",
    imgUrl: PNG8,
    price: "$499",
    inventory: 17,
  },
  {
    id: Math.random(),
    brand: "Reebok",
    name: "Reebok Ojay",
    imgUrl: PNG9,
    price: "$495",
    inventory: 13,
  },
];

export const PUMA_ARTICLES_DATA = [
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Purple",
    imgUrl: PNG1,
    price: "$299",
    inventory: 13,
  },

  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Green",
    imgUrl: PNG8,
    price: "$499",
    inventory: 17,
  },

  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Fire",
    imgUrl: PNG5,
    price: "$799",
    inventory: 12,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Bumble",
    imgUrl: PNG6,
    price: "$459",
    inventory: 6,
  },

  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Purple",
    imgUrl: PNG1,
    price: "$299",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma White",
    imgUrl: PNG2,
    price: "$199",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Khaki",
    imgUrl: PNG3,
    price: "$499",
    inventory: 3,
  },

  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Cream",
    imgUrl: PNG10,
    price: "$999",
    inventory: 5,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Black Fire",
    imgUrl: PNG11,
    price: "$699",
    inventory: 16,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma White",
    imgUrl: PNG2,
    price: "$199",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Khaki",
    imgUrl: PNG3,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Red",
    imgUrl: PNG4,
    price: "$249",
    inventory: 19,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Black & White",
    imgUrl: PNG12,
    price: "$399",
    inventory: 8,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Sky Blue",
    imgUrl: PNG13,
    price: "$699",
    inventory: 7,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Colors",
    imgUrl: PNG14,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Ojay",
    imgUrl: PNG9,
    price: "$495",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Cream",
    imgUrl: PNG10,
    price: "$999",
    inventory: 5,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Black Fire",
    imgUrl: PNG11,
    price: "$699",
    inventory: 16,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Black & White",
    imgUrl: PNG12,
    price: "$399",
    inventory: 8,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Sky Blue",
    imgUrl: PNG13,
    price: "$699",
    inventory: 7,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Long",
    imgUrl: PNG7,
    price: "$295",
    inventory: 18,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Green",
    imgUrl: PNG8,
    price: "$499",
    inventory: 17,
  },

  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Colors",
    imgUrl: PNG14,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Ghost",
    imgUrl: PNG15,
    price: "$799",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Ghost",
    imgUrl: PNG15,
    price: "$799",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Fire",
    imgUrl: PNG5,
    price: "$799",
    inventory: 12,
  },
  {
    id: Math.random(),
    brand: "Puma",
    name: "Puma Bumble",
    imgUrl: PNG6,
    price: "$459",
    inventory: 6,
  },
];

export const VANS_ARTICLES_DATA = [
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Purple",
    imgUrl: PNG1,
    price: "$299",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans White",
    imgUrl: PNG2,
    price: "$199",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Black Fire",
    imgUrl: PNG11,
    price: "$699",
    inventory: 16,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Khaki",
    imgUrl: PNG3,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Red",
    imgUrl: PNG4,
    price: "$249",
    inventory: 19,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Black & White",
    imgUrl: PNG12,
    price: "$399",
    inventory: 8,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Sky Blue",
    imgUrl: PNG13,
    price: "$699",
    inventory: 7,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Colors",
    imgUrl: PNG14,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Green",
    imgUrl: PNG8,
    price: "$499",
    inventory: 17,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Red",
    imgUrl: PNG4,
    price: "$249",
    inventory: 19,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Purple",
    imgUrl: PNG1,
    price: "$299",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans White",
    imgUrl: PNG2,
    price: "$199",
    inventory: 11,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Fire",
    imgUrl: PNG5,
    price: "$799",
    inventory: 12,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Bumble",
    imgUrl: PNG6,
    price: "$459",
    inventory: 6,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Long",
    imgUrl: PNG7,
    price: "$295",
    inventory: 18,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Ojay",
    imgUrl: PNG9,
    price: "$495",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Cream",
    imgUrl: PNG10,
    price: "$999",
    inventory: 5,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Black Fire",
    imgUrl: PNG11,
    price: "$699",
    inventory: 16,
  },

  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Long",
    imgUrl: PNG7,
    price: "$295",
    inventory: 18,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Green",
    imgUrl: PNG8,
    price: "$499",
    inventory: 17,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Ojay",
    imgUrl: PNG9,
    price: "$495",
    inventory: 13,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Cream",
    imgUrl: PNG10,
    price: "$999",
    inventory: 5,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Black Fire",
    imgUrl: PNG11,
    price: "$699",
    inventory: 16,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Black & White",
    imgUrl: PNG12,
    price: "$399",
    inventory: 8,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Sky Blue",
    imgUrl: PNG13,
    price: "$699",
    inventory: 7,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Colors",
    imgUrl: PNG14,
    price: "$499",
    inventory: 3,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Black & White",
    imgUrl: PNG12,
    price: "$399",
    inventory: 8,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Sky Blue",
    imgUrl: PNG13,
    price: "$699",
    inventory: 7,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Fire",
    imgUrl: PNG5,
    price: "$799",
    inventory: 12,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Bumble",
    imgUrl: PNG6,
    price: "$459",
    inventory: 6,
  },
  {
    id: Math.random(),
    brand: "Vans",
    name: "Vans Ghost",
    imgUrl: PNG15,
    price: "$799",
    inventory: 11,
  },
];

export const BRANDS_DATA = [
  { id: Math.random(), name: "Nike", articles: NIKE_ARTICLES_DATA.length },
  { id: Math.random(), name: "Adidas", articles: ADIDAS_ARTICLES_DATA.length },
  { id: Math.random(), name: "Reebok", articles: REEBOK_ARTICLES_DATA.length },
  { id: Math.random(), name: "Puma", articles: PUMA_ARTICLES_DATA.length },
  { id: Math.random(), name: "Vans", articles: VANS_ARTICLES_DATA.length },
];
